(cl:defpackage TTS_audio-srv
  (:use )
  (:export
   "STRINGSERVICE"
   "<STRINGSERVICE-REQUEST>"
   "STRINGSERVICE-REQUEST"
   "<STRINGSERVICE-RESPONSE>"
   "STRINGSERVICE-RESPONSE"
   "TTS"
   "<TTS-REQUEST>"
   "TTS-REQUEST"
   "<TTS-RESPONSE>"
   "TTS-RESPONSE"
   "TEXTTOSPEECH"
   "<TEXTTOSPEECH-REQUEST>"
   "TEXTTOSPEECH-REQUEST"
   "<TEXTTOSPEECH-RESPONSE>"
   "TEXTTOSPEECH-RESPONSE"
  ))

