// Generated by gencpp from file TTS_audio/StringServiceRequest.msg
// DO NOT EDIT!


#ifndef TTS_AUDIO_MESSAGE_STRINGSERVICEREQUEST_H
#define TTS_AUDIO_MESSAGE_STRINGSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace TTS_audio
{
template <class ContainerAllocator>
struct StringServiceRequest_
{
  typedef StringServiceRequest_<ContainerAllocator> Type;

  StringServiceRequest_()
    : data()  {
    }
  StringServiceRequest_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::TTS_audio::StringServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::TTS_audio::StringServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StringServiceRequest_

typedef ::TTS_audio::StringServiceRequest_<std::allocator<void> > StringServiceRequest;

typedef boost::shared_ptr< ::TTS_audio::StringServiceRequest > StringServiceRequestPtr;
typedef boost::shared_ptr< ::TTS_audio::StringServiceRequest const> StringServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::TTS_audio::StringServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::TTS_audio::StringServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::TTS_audio::StringServiceRequest_<ContainerAllocator1> & lhs, const ::TTS_audio::StringServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::TTS_audio::StringServiceRequest_<ContainerAllocator1> & lhs, const ::TTS_audio::StringServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace TTS_audio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::TTS_audio::StringServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::TTS_audio::StringServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::TTS_audio::StringServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::TTS_audio::StringServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::TTS_audio::StringServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::TTS_audio::StringServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::TTS_audio::StringServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "992ce8a1687cec8c8bd883ec73ca41d1";
  }

  static const char* value(const ::TTS_audio::StringServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x992ce8a1687cec8cULL;
  static const uint64_t static_value2 = 0x8bd883ec73ca41d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::TTS_audio::StringServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "TTS_audio/StringServiceRequest";
  }

  static const char* value(const ::TTS_audio::StringServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::TTS_audio::StringServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string data\n"
;
  }

  static const char* value(const ::TTS_audio::StringServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::TTS_audio::StringServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StringServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::TTS_audio::StringServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::TTS_audio::StringServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TTS_AUDIO_MESSAGE_STRINGSERVICEREQUEST_H
