// Generated by gencpp from file TTS_audio/StringService.msg
// DO NOT EDIT!


#ifndef TTS_AUDIO_MESSAGE_STRINGSERVICE_H
#define TTS_AUDIO_MESSAGE_STRINGSERVICE_H

#include <ros/service_traits.h>


#include <TTS_audio/StringServiceRequest.h>
#include <TTS_audio/StringServiceResponse.h>


namespace TTS_audio
{

struct StringService
{

typedef StringServiceRequest Request;
typedef StringServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StringService
} // namespace TTS_audio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::TTS_audio::StringService > {
  static const char* value()
  {
    return "7229f1b0de733d7956dd646adcbf7e06";
  }

  static const char* value(const ::TTS_audio::StringService&) { return value(); }
};

template<>
struct DataType< ::TTS_audio::StringService > {
  static const char* value()
  {
    return "TTS_audio/StringService";
  }

  static const char* value(const ::TTS_audio::StringService&) { return value(); }
};


// service_traits::MD5Sum< ::TTS_audio::StringServiceRequest> should match
// service_traits::MD5Sum< ::TTS_audio::StringService >
template<>
struct MD5Sum< ::TTS_audio::StringServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::TTS_audio::StringService >::value();
  }
  static const char* value(const ::TTS_audio::StringServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::TTS_audio::StringServiceRequest> should match
// service_traits::DataType< ::TTS_audio::StringService >
template<>
struct DataType< ::TTS_audio::StringServiceRequest>
{
  static const char* value()
  {
    return DataType< ::TTS_audio::StringService >::value();
  }
  static const char* value(const ::TTS_audio::StringServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::TTS_audio::StringServiceResponse> should match
// service_traits::MD5Sum< ::TTS_audio::StringService >
template<>
struct MD5Sum< ::TTS_audio::StringServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::TTS_audio::StringService >::value();
  }
  static const char* value(const ::TTS_audio::StringServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::TTS_audio::StringServiceResponse> should match
// service_traits::DataType< ::TTS_audio::StringService >
template<>
struct DataType< ::TTS_audio::StringServiceResponse>
{
  static const char* value()
  {
    return DataType< ::TTS_audio::StringService >::value();
  }
  static const char* value(const ::TTS_audio::StringServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TTS_AUDIO_MESSAGE_STRINGSERVICE_H
