// Generated by gencpp from file TTS_audio/TextToSpeechResponse.msg
// DO NOT EDIT!


#ifndef TTS_AUDIO_MESSAGE_TEXTTOSPEECHRESPONSE_H
#define TTS_AUDIO_MESSAGE_TEXTTOSPEECHRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace TTS_audio
{
template <class ContainerAllocator>
struct TextToSpeechResponse_
{
  typedef TextToSpeechResponse_<ContainerAllocator> Type;

  TextToSpeechResponse_()
    : success(false)
    , message()  {
    }
  TextToSpeechResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::TTS_audio::TextToSpeechResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::TTS_audio::TextToSpeechResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TextToSpeechResponse_

typedef ::TTS_audio::TextToSpeechResponse_<std::allocator<void> > TextToSpeechResponse;

typedef boost::shared_ptr< ::TTS_audio::TextToSpeechResponse > TextToSpeechResponsePtr;
typedef boost::shared_ptr< ::TTS_audio::TextToSpeechResponse const> TextToSpeechResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::TTS_audio::TextToSpeechResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::TTS_audio::TextToSpeechResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::TTS_audio::TextToSpeechResponse_<ContainerAllocator1> & lhs, const ::TTS_audio::TextToSpeechResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::TTS_audio::TextToSpeechResponse_<ContainerAllocator1> & lhs, const ::TTS_audio::TextToSpeechResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace TTS_audio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::TTS_audio::TextToSpeechResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::TTS_audio::TextToSpeechResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::TTS_audio::TextToSpeechResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::TTS_audio::TextToSpeechResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::TTS_audio::TextToSpeechResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::TTS_audio::TextToSpeechResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::TTS_audio::TextToSpeechResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::TTS_audio::TextToSpeechResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::TTS_audio::TextToSpeechResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "TTS_audio/TextToSpeechResponse";
  }

  static const char* value(const ::TTS_audio::TextToSpeechResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::TTS_audio::TextToSpeechResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success  # 服务是否成功\n"
"string message  # 返回的消息\n"
"\n"
;
  }

  static const char* value(const ::TTS_audio::TextToSpeechResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::TTS_audio::TextToSpeechResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TextToSpeechResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::TTS_audio::TextToSpeechResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::TTS_audio::TextToSpeechResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TTS_AUDIO_MESSAGE_TEXTTOSPEECHRESPONSE_H
