// Generated by gencpp from file TTS_audio/TextToSpeech.msg
// DO NOT EDIT!


#ifndef TTS_AUDIO_MESSAGE_TEXTTOSPEECH_H
#define TTS_AUDIO_MESSAGE_TEXTTOSPEECH_H

#include <ros/service_traits.h>


#include <TTS_audio/TextToSpeechRequest.h>
#include <TTS_audio/TextToSpeechResponse.h>


namespace TTS_audio
{

struct TextToSpeech
{

typedef TextToSpeechRequest Request;
typedef TextToSpeechResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TextToSpeech
} // namespace TTS_audio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::TTS_audio::TextToSpeech > {
  static const char* value()
  {
    return "191f0a61ba3a929ce6cac14343f74651";
  }

  static const char* value(const ::TTS_audio::TextToSpeech&) { return value(); }
};

template<>
struct DataType< ::TTS_audio::TextToSpeech > {
  static const char* value()
  {
    return "TTS_audio/TextToSpeech";
  }

  static const char* value(const ::TTS_audio::TextToSpeech&) { return value(); }
};


// service_traits::MD5Sum< ::TTS_audio::TextToSpeechRequest> should match
// service_traits::MD5Sum< ::TTS_audio::TextToSpeech >
template<>
struct MD5Sum< ::TTS_audio::TextToSpeechRequest>
{
  static const char* value()
  {
    return MD5Sum< ::TTS_audio::TextToSpeech >::value();
  }
  static const char* value(const ::TTS_audio::TextToSpeechRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::TTS_audio::TextToSpeechRequest> should match
// service_traits::DataType< ::TTS_audio::TextToSpeech >
template<>
struct DataType< ::TTS_audio::TextToSpeechRequest>
{
  static const char* value()
  {
    return DataType< ::TTS_audio::TextToSpeech >::value();
  }
  static const char* value(const ::TTS_audio::TextToSpeechRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::TTS_audio::TextToSpeechResponse> should match
// service_traits::MD5Sum< ::TTS_audio::TextToSpeech >
template<>
struct MD5Sum< ::TTS_audio::TextToSpeechResponse>
{
  static const char* value()
  {
    return MD5Sum< ::TTS_audio::TextToSpeech >::value();
  }
  static const char* value(const ::TTS_audio::TextToSpeechResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::TTS_audio::TextToSpeechResponse> should match
// service_traits::DataType< ::TTS_audio::TextToSpeech >
template<>
struct DataType< ::TTS_audio::TextToSpeechResponse>
{
  static const char* value()
  {
    return DataType< ::TTS_audio::TextToSpeech >::value();
  }
  static const char* value(const ::TTS_audio::TextToSpeechResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TTS_AUDIO_MESSAGE_TEXTTOSPEECH_H
